spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: healthcheck
              uri: ${HEALTHCHECK_URL:http://localhost:8081}
              predicates:
                - Path=/healthcheck/**
            - id: user-users
              uri: ${USER_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/users/**
            - id: user-roles
              uri: ${USER_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/roles/**
            - id: expense-categories
              uri: ${EXPENSE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/categories/**
            - id: expense-records
              uri: ${EXPENSE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/records/**
            - id: currency
              uri: ${CURRENCY_URL:http://localhost:8084}
              predicates:
                - Path=/api/v1/currencies/**
            - id: auth
              uri: ${AUTH_URL:http://localhost:8085}
              predicates:
                - Path=/api/v1/auth/**


app:
  gateway:
    open-endpoints:
      - /api/v1/auth/**
      - /healthcheck
      - /public/**

auth:
  jwt:
    access-token-ttl-sec: 86400
    secret-key: classpath:keys/key.pem

server:
  port: 8080