spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: healthcheck
              uri: ${HEALTHCHECK_URL:http://localhost:8081}
              predicates:
                - Path=/healthcheck/**
            - id: user-users
              uri: ${USER_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/users/**
            - id: user-roles
              uri: ${USER_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/roles/**
            - id: expense-categories
              uri: ${EXPENSE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/categories/**
            - id: expense-records
              uri: ${EXPENSE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/records/**
            - id: currency
              uri: ${CURRENCY_URL:http://localhost:8084}
              predicates:
                - Path=/api/v1/currencies/**
